const brandlistUrl = 'https://mct.auto.qq.com/index.php?mod=interface&act=brandlist' //汽车大全

//指定
// 输入：brandid 
const serialListUrl = 'https://mct.auto.qq.com/index.php?mod=interface&act=serialList'

// const baseUrl ="http://localhost:8601/"
const baseUrl = "https://api.ultimate-factory.com/car/"

module.exports  = {
  brandlistUrl,
  serialListUrl, 
  getContentList: baseUrl +'apimp/getContentList',
  getContentById: baseUrl +'apimp/getContentById',
  getOrgAndPartner: baseUrl +'apimp/getOrgAndPartner',
  getDictDetail: baseUrl + 'apimp/getDictDetail',
  getServiceListByType: baseUrl + 'apimp/getServiceListByType',
  loginByWeixin: baseUrl +'apimp/loginByWeixin',
  updateMemberInfo: baseUrl +'apimp/updateMemberInfo',
  addCars: baseUrl +'apimp/addCars',
  getCarsByOpenid: baseUrl +'apimp/getCarsByOpenid',
  getMemberByOpenid: baseUrl +'apimp/getMemberByOpenid',
  getMallInfoById: baseUrl +'apimp/getMallInfoById',
  getOrderByWexin: baseUrl +'apimp/getOrderByWexin',
  getMallByPage: baseUrl +'apimp/getMallByPage',
  getMallDetailById: baseUrl +'apimp/getMallDetailById',
  getCartCount: baseUrl +'apimp/getCartCount',
  addToCart: baseUrl +'apimp/addToCart',
  deleteCarById: baseUrl +'apimp/deleteCarById',
  getCartListByPage: baseUrl +'apimp/getCartListByPage',
  getMemberAddress: baseUrl +'apimp/getMemberAddress',
  getAddressDetailById: baseUrl +'apimp/getAddressDetailById',
  getDefaultAddress: baseUrl +'apimp/getDefaultAddress',
  updateThenMemberAdd: baseUrl +'apimp/updateThenMemberAdd',
  getProvinceData: baseUrl + 'apimp/getProvinceData',
  getCityData: baseUrl + 'apimp/getCityData',
  getDistrictData: baseUrl + 'apimp/getDistrictData',
  delAddressById: baseUrl +'apimp/delAddressById',
  getOrderByMoreMall: baseUrl +'apimp/getOrderByMoreMall',
  getOrderListByPage: baseUrl +'apimp/getOrderListByPage',
  getIndexMallByPage: baseUrl +'apimp/getIndexMallByPage',
  getGroupMallByPage: baseUrl +'apimp/getGroupMallByPage',
  getQuestion: baseUrl +'apimp/getQuestion',
  addToGroup: baseUrl +'apimp/addToGroup',
  getGroupListByPage: baseUrl +'apimp/getGroupListByPage',
  getCheckReportList: baseUrl +'apimp/getCheckReportList',
  getCheckDetail:baseUrl +'apimp/getCheckDetail',
  getVerCode: baseUrl +'apimp/getVerCode',
  paySuccessResult: baseUrl +'apimp/paySuccessResult',
  continuedPayment: baseUrl +'apimp/continuedPayment',
  getServiceOrderByCart: baseUrl +'apimp/getServiceOrderByCart',
  uptServiceOrderTime: baseUrl +'apimp/uptServiceOrderTime',
  addComment: baseUrl +'apimp/addComment',
  deleteCartById: baseUrl +'apimp/deleteCartById',
  getMemberScoreList: baseUrl +'apimp/getMemberScoreList',
  getMemberVideo: baseUrl +'apimp/getMemberVideo',
  setDefaultCar: baseUrl +'apimp/setDefaultCar',
  getDefaultCar: baseUrl + 'apimp/getDefaultCar',
  getOrderDetailById: baseUrl +'apimp/getOrderDetailById',
  getMemberById: baseUrl +'apimp/getMemberById',
  getDiffGroupMan: baseUrl +'apimp/getDiffGroupMan',
  checkQuestionTimes: baseUrl +'apimp/checkQuestionTimes',
  getQuestionPrize: baseUrl + 'apimp/getQuestionPrize',
  getCouponList: baseUrl + 'apimp/getCouponList',
}